threescale_template: https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/master/amp/amp.yml
#threescale_template: file:///tmp/3scale-amp-2.2.yml

modified_template_path: /home/ahameed/dev/temp/amp.yml

threescale_project: "{{OCP_PROJECT_PREFIX}}-3scale-ansible"
threescale_tenant_name: "{{OCP_PROJECT_PREFIX}}-3scale-ansible"
threescale_wildcard_domain: "{{ openshift_master_default_subdomain }}"
threescale_delay: 10
threescale_retries: 30

amp_admin_passwd: admin

vertx_stage_route: {routename: "vertx-staging-apicast-route", hostname: "vertx-stage-apicast-{{OCP_PROJECT_PREFIX}}.{{ threescale_wildcard_domain }}" }
vertx_prod_route: {routename: "vertx-prod-apicast-route", hostname: "vertx-prod-apicast-{{OCP_PROJECT_PREFIX}}.{{ threescale_wildcard_domain }}" }

API_RESPONSE_DIR:  /home/ahameed/dev/temp
PROVISION_3SCALE_LOG_FILE: "{{ API_RESPONSE_DIR }}/refresh_3scale_resources.log"
